[project]
name = "kube-schedule-scaler-threaded"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "croniter==2.0.7",
    "pykube-ng==23.6.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
